// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDos.Data;

#nullable disable

namespace ToDos.Data.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20250820154213_DateTimeOffsetConvertersAgain")]
    partial class DateTimeOffsetConvertersAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ToDos.Data.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DueDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted", "DueDate");

                    b.ToTable("ToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
